[package]

name = "demo_sidechain"
version = "1.0.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.0"
secp256k1 = "0.22"

[[bin]]
name = "main"
path = "src/main.rs"

[workspace]
members = [
    "main",   # This should be the directory paths to the member crates
    "block",
    "rpc"
]